name: CI 
on:
  pull_request: 
    branches: [develop]

  jobs:
    builds:
      runs-on: ubuntu-latest
      steps:
        - use: actions/checkout@v2
        - name: Use NodeJs
          uses: actions/setup-node@v1
          with: 
            node-version: "12.x"
        - run: npm ci #npm ci vs npm install
        - run: npm run format:check
        - run: npm test -- --coverage
          env: 
            CI: true 